### ISSUE TITLE
Knockout Task Scheduler

### ISSUE THREAD

**Issue by AdamWillden** [brianmhunt/knockout-fast-foreach#20]
@brianmhunt after we looked into batching for the knockout components ([see here](https://github.com/knockout/knockout/pull/1659)) mbest appeared to use the new task scheduler ([see here ](https://github.com/knockout/knockout/pull/1738)). I know you use `FastForEach.animateFrame` here which is similar to the batching we looked into.

Is there any benefit in considering the use of the task scheduler here once released?

**Comment by brianmhunt** [comment]
@AdamWillden It's a good question, and I had mulled it too as @mbest was making the patches to the knockout main.

The advantage of animation frames is basically power-friendliness i.e. the browser tab will sleep when not active, even if there are deferred events going on.

The advantage of the task scheduler is that it has sub-redraw asynchronous behaviour i.e. the asynchronous events happen faster than redraws, so it may be performance preferable.

It is possible `ko.tasks` will lead to choppiness – the longer the frame window the more events are bulked together and the fewer the redraws, and `ko.tasks` has the shortest possible frame interval. Animation frames on the other hand tend to have relatively long intervals.

I do not know, but would be interested in some comparisons, of the two techniques from a performance perspective. Even then, though, it is not just performance that is a consideration but power consumption – especially as more things go mobile.

For the moment I am going to stick with `animationFrame` since it seems to hold to the broader policy choice – until we have some evidence.

That said, I would be happy to accept a PR that made the asynchronous behaviour configurable so that `ko.tasks` could be used if desired.

**Comment by AdamWillden** [comment]
I applaud you for that reply!

You don't have to keep this open. I won't be submitting a PR any time too soon to configure the async option as I dont have any immediate need to test it. It just occurred to me there might be some benefit here and wondered if you'd considered it yourself ...and you had.

I'm intrigued to know what makes ko.tasks have "sub-redraw asynchronous behaviour" and to really understand what that means! I'll have to look into the code!

Thanks for helping me to understand. I've learnt lots from watching ko related development! I'll close this :-)

**Comment by brianmhunt** [comment]
@AdamWillden My pleasure!

Here's the relevant bit of sub-redraw async behaviour:

https://github.com/knockout/knockout/blob/master/src/tasks.js#L8-L15

In particular you'll want to look up mutation observers, and [other techniques](http://stackoverflow.com/questions/19906947)

Cheers
