### ISSUE TITLE
Fastforeach and template

### ISSUE THREAD

**Issue by Sisco21** [brianmhunt/knockout-fast-foreach#44]
Hello,

I'm unable to use fastForeach and templates. Could you help me?

Thanks

**Comment by cervengoc** [comment]
Would you please describe your problem in more detail? Some example code, or an example on jsfiddle.net would be even better.

**Comment by Sisco21** [comment]
Thanks for your answer.

I've got this which is working

`<div class="daily-content--zoomzone" id="dailyContainer" data-bind="foreach:  planningData()">
                <div class="daily-content--ue context-menu-ue" data-bind="visible: isVisible()">
                    <div class="daily-content--ue--title" data-bind="text: ueIdentifier">
                    </div>
                    <div class="daily-content--ue--container" data-bind="template: { name: 'sector-template', foreach:  sortedSectors }"></div>
                </div>
            </div>`

and i've got the template
`<script type="text/html" id="sector-template">
    <article class="area" data-bind="attr:{'data-entitytype': entityType, 'data-sortorder' : sortOrder, 'data-sectorid': identifier},visible: (!isVirtual() && isVisible()) || (isVirtual() && $root.userPreferences().showVirtualObjects)" ondrop="dailyPlanningVm.dropOnSector(event)" ondragover="dailyPlanningVm.allowDropOnSector(event)">
        <div class="area--title" data-bind="attr:{draggable: !isVirtual() && !$root.isPresenter() ? $root.allowDragAndDrop : false},style:{ border: isVirtual() ? 'dashed' : ''},css: { 'context-menu-sector': !isVirtual()  }" onclick=" dailyPlanningVm.onClickSector(event) " ondragstart="dailyPlanningVm.dragStartSector(event)">
            <div class=" area--title--color" data-bind="style: { background: colorCode}"></div><span data-bind="text: label"></span>
        </div>
        <div class="area--chantier--container" data-bind="template: { name: 'job_template', foreach:  jobsByColumn() }">
        </div>
    </article>
</script>`

But unable to display informations.

I've got this error : 

> Uncaught ReferenceError: Unable to process binding "template: function (){return { name:'sector-template',fastForeach:sortedSectors} }"
> Message: Unable to process binding "attr: function (){return {'data-entitytype':entityType,'data-sortorder':sortOrder,'data-sectorid':identifier} }"
> Message: entityType is not defined

Object seems to be disappeared

**Comment by cervengoc** [comment]
When you write "foreach" in a `template` binding configuration, it actually doesn't refer to the `foreach` binding, but to a `template` binding parameter. As `template` binding doesn't have a `fastForEach` parameter, you'll get the error.

Instead of using the `template` binding with the foreach syntax, you can use the `fastForEach` binding with its template syntax, like this.

```
fastForEach: { name: 'sector-template', data: sortedSectors }
```

Be aware that `fastForEach` doesn't use the template binding internally for this syntax. If you need to use the `template` binding, I suggest you introduce another level of binding, like this.

```
<div data-bind="fastForEach: myArray">
  <!-- ko template: { name: 'my-template' } -->
  <!-- /ko -->
</div>
```

In my opinion this latter way is more readable and safe. If your markup can have another wrapper `div`, then you don't even need the containerless syntax inside `fastForEach`.

**Comment by Sisco21** [comment]
Dear cervengoc,

Thanks for your answser, Your right and that works great.

The code is 40% faster than before.

Thanks again and great job.
